### ISSUE TITLE
The patch replacement feature does not work

### ISSUE THREAD

**Issue by Leg-rings** [Grasscutters/Cultivation#200]
I'm using the Yuanshen client (4.0.1), but when I launch the game, the patch replacement feature doesn't seem to work, the patch command window doesn't launch, but launches the game directly

**Comment by Leg-rings** [comment]
It seems that I can manually replace the version.dll in the Cultivation folder with a mhypbase.dll, but the auto-replace feature doesn't work

**Comment by NotThorny** [comment]
version.dll isn't a normal file from the game, so it's not actually being replaced. It's being moved into the game folder, so if Cultivation isn't moving the file with version.dll, then the same behavior would occur with mhypbase.
There are rare cases where people need to use mhypbase instead of version.dll, but it _isn't_ because Cultivation can't move the file. That would be because of your system.

What you can do is manually place version.dll into your game folder, then rename your original mhypbase to mhypbase.dll.bak, and then rename version.dll to mhypbase.dll

Cultivation checks if you're already patched that way and skips it. That means Cultivation also won't unpatch you, just as a heads up.
