### ISSUE TITLE
The game crashes when trying to open

### ISSUE THREAD

**Issue by Rimuti** [Grasscutters/Cultivation#206]
I did everything correctly as I saw in the videos and even checked on the page, but whenever I open the game it not only takes a long time to load but also crashes whenever the world is about to open and returns to the launcher screen. How do I resolve this? Is it something in the game? In the program? In mods? On the computer? I do not know what else to do...

**Comment by NotThorny** [comment]
This would be an issue with your game or your server/account, not Cultivation. You should instead check your game files and see when/where specifically the game is crashing (same every time?). I'd suggest taking it to a [support channel in discord](https://discord.gg/T5vZU6UyeG) for better help, since it's not a problem with Cultivation itself.
