### ISSUE TITLE
cant patch

### ISSUE THREAD

**Issue by jakeal123** [Grasscutters/Cultivation#244]
i cant patch it. i understand that i need to revert my game version but noone will actually tell me how and the stupid link it no help whatsoever. would someone please tell me how to change my game version. or give me a link to something that ACTUALLY explains it. ive been trying to figure it out for weeks now.

**Comment by NotThorny** [comment]
Sorry to hear you're confused about how downloading the game works. To download the game, you need to do what the setup guide for Grasscutter says to do, and go to the game client link. 
https://github.com/Grasscutters/Grasscutter?tab=readme-ov-file#quick-setup-guide
Once there, you select the game data you need, which is almost guaranteed to be the whole (full install) game data since I strongly doubt you have a lower version client to use an hdiff with. A zip file is an archive file that can be extracted using an extraction program such as winrar or 7zip.

After the game zip has been downloaded, you extract it. Congrats you now have the game!
