### ISSUE TITLE
Resources download stuck after 5 seconds with no progress bar change

### ISSUE THREAD

**Issue by Lunairayz** [Grasscutters/Cultivation#88]
launched as administrator, downloaded latest grasscutter (not data), then started resources.
used msi installer (although the shortcut doesn't force open administrator)

![image](https://user-images.githubusercontent.com/45308130/188701127-ebdc8a1a-47fb-4c3b-9822-3ee169146654.png)

**Comment by Arikatsu** [comment]
Progress bar will stay greyed out during extraction process. Resources are big, when they are extracted it will say finished on its own. There won't be any change to progress bar. That only happens when downloading.

**Comment by Lunairayz** [comment]
> Progress bar will stay greyed out during extraction process. Resources are big, when they are extracted it will say finished on its own. There won't be any change to progress bar. That only happens when downloading.

a fast download but a agonizingly slow extraction? I had 2gb archives extract faster tbh

**Comment by Lunairayz** [comment]
> Progress bar will stay greyed out during extraction process.
> Resources are big

a fast download but an agonizingly slow extraction? I had 2gb archives extract in under 2 minutes tbh

**Comment by SpikeHD** [comment]
> a fast download but an agonizingly slow extraction? I had 2gb archives extract in under 2 minutes tbh

yes, unlike the archives you are probably talking about, GC resources are tens of thousands of teeny little files, no more than a few kilobytes or, rarely, megabytes. This causes a lot of overhead since the OS has to perform operations before and after each file is written, and since there are so many, it adds up.

seeing as this has not been updated in a week, I'll be closing this
